### ISSUE TITLE
sharing of your P1 project

### ISSUE THREAD

**Issue by aeonSolutions** [WhoSayIn/esp8266_dsmr2mqtt#3]
Hi @WhoSayIn 
great work!
I'm sharing your P1 meter project on my own home automation project repository:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home-Automation/README.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home-Automation/README.md)

**Comment by aeonSolutions** [comment]
<img height="250px" alt="pcb_layout" src="https://github.com/WhoSayIn/esp8266_dsmr2mqtt/assets/7936768/2bd240b0-432c-4fc4-8b72-925c74a98fe3">

**Comment by WhoSayIn** [comment]
Sure thing @aeonSolutions 

Keep in mind that this is not under active development anymore. ESPHome introduced DSMR functionality and I personally switched to that as well.

https://esphome.io/components/sensor/dsmr.html

**Comment by aeonSolutions** [comment]
thanks
